### ISSUE TITLE
Error: Invalid version "auto".

### ISSUE THREAD

**Issue by AnjumShakeelJanjua** [game-ci/unity-test-runner#131]
I am getting issue with Unity Test Runner with error below:

![Screen Shot 2021-07-01 at 3 32 07 AM](https://user-images.githubusercontent.com/16688695/124039908-474bf880-da1d-11eb-8581-8b9c738c2cac.png)

Followed this tutorial from [https://game.ci/docs/github/test-runner](url)
Below is the yml file:
https://paste.myst.rs/k7xo0pp3

**Comment by GabLeRoux** [comment]
Did you update `projectPath: path/to/your/project` with actual path to your project? You can also remove the line if your unity project is located at the root for your repository.

Concerning the Invalid version "auto", I think it might be due to a `tag` named `auto`. Right now, `unity-builder` action expects to have git tags that are [semver.](https://semver.org/) so maybe it failed due to this.

Try pushing a tag that looks something like `v0.0.1` or `v1.0.0` and try to run the actions again.

**Comment by AnjumShakeelJanjua** [comment]
Here are the screenshots of my project path:
![Screen Shot 2021-07-02 at 1 28 05 AM](https://user-images.githubusercontent.com/16688695/124186035-27780b80-dad5-11eb-8fa4-ffd27176b7f1.png)

![Screen Shot 2021-07-02 at 1 28 27 AM](https://user-images.githubusercontent.com/16688695/124186046-2d6dec80-dad5-11eb-911e-bb70f93aecb1.png)

I also removed the line as you said because of my project being in the root directory. 
https://paste.myst.rs/hqou8rdk

But it still gives the same error.

**Comment by webbertakken** [comment]
Currently you have test runner in that workflow but the project is never checked out in your workflow.

Our readme will guide you through the appropriate steps to set it up. 

Please note especially the first two sections on the [getting started](https://game.ci/docs/github/getting-started) part before continuing.

**Comment by davidmfinol** [comment]
Closing as this should be resolved.
@AnjumShakeelJanjua can re-open if still facing an issue.
