### ISSUE TITLE
Add workflow with customParameters in it

### ISSUE THREAD

**Issue by dginovker** [game-ci/unity-test-runner#163]
**Context**

I'm trying to see how I can use `customParameters` to run my tests on the Android platform instead of the default (PC, Mac & Linux Standalone), but neither in the [Documentation](https://game.ci/docs/github/test-runner#complete-example) or the [project workflows](https://github.com/game-ci/unity-test-runner/tree/main/.github/workflows) is there an example on how customParameters is used.

**Suggested solution**

Create a workflow in the [project workflows](https://github.com/game-ci/unity-test-runner/tree/main/.github/workflows) that passes in even the most basic custom parameter - maybe a parameter that is logged out during an editor test or something

**Considered alternatives**

Asking in Discord where [no one else would see the answer](https://knockout.chat/thread/33251/1)

**Additional details**

Thanks for the library btw 😄

**Comment by timcassell** [comment]
`customParameters` are extra parameters for Unity's test runner which this project doesn't explicitly support (see [test runner docs](https://docs.unity3d.com/Packages/com.unity.test-framework@1.1/manual/reference-command-line.html) for the arguments that you can use as `customParameters`).

This project currently doesn't support target platform tests, as they do not work in Docker. For obvious reasons, Android tests will never be able to work in Docker unless you could somehow hook up an Android emulator. If you are using a self-hosted runner instead of github-hosted runner, you may be able to get Android or any other target platform tests to work, but not with this repo as it currently is.

I made a [fork of this repo](https://github.com/timcassell/unity-test-runner/tree/targetPlatform) where I tried to get target platform tests to work, but was unable to simply because they do not work in Docker. If you are using a self-hosted runner, you could try using my fork (on the `targetPlatform` branch) to see if it will work for you.

**Comment by dginovker** [comment]
Super handy info and links. Test runner docs linked as a note to the customParameters info in the gameci documentation would probably have saved me that time 👍 

Out of curiosity - I can't run the Android platform tests, but can I set the Editor to Android before running them?

Many thanks!

**Comment by timcassell** [comment]
> Super handy info and links. Test runner docs linked as a note to the customParameters info in the gameci documentation would probably have saved me that time +1

I agree. Perhaps you could make a PR with that change?

> Out of curiosity - I can't run the Android platform tests, but can I set the Editor to Android before running them?

game-ci will use whatever configuration your project is already set to. If you need to change the build target during your CI, I think you can pass `-buildTarget Android` as a `customParameters` (see https://docs.unity3d.com/Manual/EditorCommandLineArguments.html). That's an editor argument, so I'm not 100% if it also works with the test runner, but if it doesn't, you can also manually edit the project settings file before running the tests.

**Comment by timcassell** [comment]
Ah yeah, I forgot about that part. That's a pretty niche use-case, but I do see the value in it.

Unity is currently working on official Docker support, and I'm really hoping target platform tests will just work once they finally do, then it would be nice to support it fully in game-ci.

Also see for more information: https://forum.unity.com/threads/unity-test-framework-2-0-ready-for-feedback.1230126/#post-7896961
