### ISSUE TITLE
cannot access  '/github/workspace/CodeCoverage': No such file or directory

### ISSUE THREAD

**Issue by hannesdelbeke** [game-ci/unity-test-runner#252]
**Bug description**

```
###########################
#    COMBINE_RESULTS Results    #
###########################

chmod: cannot access '/github/workspace/CodeCoverage': No such file or directory
Changing to "/github/workspace/_activate-license" directory.
/github/workspace/_activate-license /github/workspace
/github/workspace

###########################
#         Failure         #
###########################

Please note that the exit code is not very descriptive.
Most likely it will not help you solve the issue.

To find the reason for failure: please search for errors in the log above.

Error: The process '/usr/bin/docker' failed with exit code 1
```
https://github.com/Anthogonyst/Synesthesia/actions/runs/7201350807/job/19617259886

**How to reproduce**

i just make a buid.
and it fails on test.
i m not sure if the project actually has tests or not.

- **Expected behavior**

**Additional details**

**Comment by GabLeRoux** [comment]
There's a few problems with the linked repository:

1. The Library folder is tracked, it shouldn't be. Make sure you use proper .gitignore and then get rid of files that should be ignored:

```bash
git rm -rf . && git clean -xdf && git add .
git commit -m "Remove files that should be ignored"
git push
```

2. The project doesn't have tests

You're trying to run unity-test-runner to execute Playmode and Editmode tests, but there are none in the project. If you're only looking to automate the builds, you can delete the parts in the yaml workflow that executes the tests.

3. I recommend using the parallel workflow example from our docs instead of running everything sequentially. This might cause troubles with excessive space use by downloading multiple docker images on a single action run.

See this example here:

https://game.ci/docs/github/getting-started#parallel-execution-of-tests-and-builds

**Comment by GabLeRoux** [comment]
Here's a PR that showcases the fixes. Note: I did not fix the video and I did not try the generated build.

https://github.com/Anthogonyst/Synesthesia/pull/1

**Comment by GabLeRoux** [comment]
I'm closing this as I demonstrated in related pull-request that there is no problem with the CI. Don't hesitate to create other issues, reply here or chat on our discord server.

Good luck :)

**Comment by hannesdelbeke** [comment]
Thanks for the lightning fast feedback on this 🤯

**Comment by Anthogonyst** [comment]
This is amazing. Thank you so much!
