### ISSUE TITLE
Is it possible to cache the Unity Engine Docker image instead of having to download it each time?

### ISSUE THREAD

**Issue by sindre0830** [game-ci/unity-test-runner#289]
I am referencing this first part of the job run:

```
Unable to find image 'unityci/editor:ubuntu-6000.0.29f1-linux-il2cpp-3' locally
ubuntu-6000.0.29f1-linux-il2cpp-3: Pulling from unityci/editor
```

The job currently takes over 7 minutes and hoping to reduce this.

**Comment by webbertakken** [comment]
A few things to consider:

On GitHub hosted runners the pull is fairly quick, because the network between DockerHub (on AWS I believe) and Azure is fast.

Container images are already sent in a compressed format and if the network is fast, it is basically as if you're pulling from cache.

If the network between your runner and the docker registry is slow, you could consider setting up a docker cache, like that of Artifactory or similar software. These services usually also provide image scanning and other security features.

When using self-hosted runners that are not ephemeral, you could reuse docker layers that you pulled from the runners local docker installation.

What you can not do, for example, is cache the docker image in actions/cache, because of the size limitations (not that it would be faster either way). Even if you'd cache it directly on a storage bucket it typically wouldn't be faster.

**Comment by davidmfinol** [comment]
Relevant discussion on Discord: https://discord.com/channels/710946343828455455/1307492964380971020/1307847046077878325

**Comment by sindre0830** [comment]
Thank you for the detailed answer. Closing this issue.
